Watching for file changes with StatReloader
Watching for file changes with StatReloader
[31/May/2020 18:44:36] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 18:44:44] "POST /met/ HTTP/1.1" 200 908
[31/May/2020 18:44:49] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 18:44:50] "GET /static/css/style.css HTTP/1.1" 304 0
[31/May/2020 18:45:30] "POST /bmr/ HTTP/1.1" 200 993
[31/May/2020 18:45:42] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 18:47:19] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 18:47:20] "GET /static/css/style2.css HTTP/1.1" 304 0
[31/May/2020 18:52:41] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 18:52:42] "GET /static/css/style.css HTTP/1.1" 304 0
[31/May/2020 18:52:51] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 18:52:51] "GET /static/css/style2.css HTTP/1.1" 304 0
[31/May/2020 18:58:08] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 18:58:08] "GET /static/images/bmr2.jpg HTTP/1.1" 304 0
[31/May/2020 18:58:23] "POST /bmr/ HTTP/1.1" 200 993
[31/May/2020 18:58:29] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 18:58:36] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 18:58:37] "GET /static/css/style2.css HTTP/1.1" 304 0
[31/May/2020 18:58:37] "GET /static/images/met2.jpg HTTP/1.1" 304 0
[31/May/2020 18:58:51] "POST /met/ HTTP/1.1" 200 909
[31/May/2020 18:58:55] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 18:59:18] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 18:59:18] "GET /static/css/style.css HTTP/1.1" 200 460
[31/May/2020 18:59:20] "GET /static/images/bmr2.jpg HTTP/1.1" 200 2467163
Not Found: /favicon.ico
[31/May/2020 18:59:20] "GET /favicon.ico HTTP/1.1" 404 2484
[31/May/2020 18:59:30] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 18:59:30] "GET /static/css/style2.css HTTP/1.1" 200 596
[31/May/2020 18:59:31] "GET /static/images/met2.jpg HTTP/1.1" 200 157171
[31/May/2020 19:00:05] "POST /bmr/ HTTP/1.1" 200 1893
[31/May/2020 19:00:12] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 19:00:12] "GET /static/images/bmr2.jpg HTTP/1.1" 304 0
[31/May/2020 19:00:19] "POST /bmr/ HTTP/1.1" 200 1893
[31/May/2020 19:00:44] "POST /met/ HTTP/1.1" 200 909
[31/May/2020 19:00:55] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 19:01:11] "POST /met/ HTTP/1.1" 200 906
[31/May/2020 19:01:16] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 19:01:19] "POST /met/ HTTP/1.1" 200 906
[31/May/2020 19:01:31] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 19:01:38] "POST /met/ HTTP/1.1" 200 906
[31/May/2020 19:01:41] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 19:01:45] "POST /met/ HTTP/1.1" 200 910
[31/May/2020 19:01:49] "GET /met/ HTTP/1.1" 200 1959
[31/May/2020 19:01:53] "POST /bmr/ HTTP/1.1" 200 1893
[31/May/2020 19:02:08] "POST /bmr/ HTTP/1.1" 200 981
[31/May/2020 19:02:29] "POST /bmr/ HTTP/1.1" 200 981
[31/May/2020 19:02:45] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 19:03:12] "POST /bmr/ HTTP/1.1" 200 993
[31/May/2020 19:03:12] "GET /static/css/style.css HTTP/1.1" 304 0
[31/May/2020 19:03:33] "GET /bmr/ HTTP/1.1" 200 1671
[31/May/2020 19:03:45] "POST /bmr/ HTTP/1.1" 200 981
[31/May/2020 19:04:43] "GET /met/ HTTP/1.1" 200 1959
Not Found: /
[31/May/2020 19:04:43] "GET / HTTP/1.1" 404 2433
[31/May/2020 19:04:43] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[31/May/2020 19:04:43] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[31/May/2020 19:04:43] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /
[31/May/2020 20:46:03] "GET / HTTP/1.1" 404 2433
[01/Jun/2020 03:36:25] "GET /met/ HTTP/1.1" 200 1959
[01/Jun/2020 03:36:26] "GET /static/images/met2.jpg HTTP/1.1" 200 157171
Not Found: /favicon.ico
[01/Jun/2020 03:36:26] "GET /favicon.ico HTTP/1.1" 404 2484
[01/Jun/2020 03:37:04] "GET /bmr/ HTTP/1.1" 200 1671
[01/Jun/2020 03:37:05] "GET /static/images/bmr2.jpg HTTP/1.1" 200 2467163
----------------------------------------
Exception happened during processing of request from ('104.152.52.29', 45867)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[01/Jun/2020 06:47:24] "GET /bmr/ HTTP/1.1" 200 1671
[01/Jun/2020 06:47:24] "GET /static/css/style.css HTTP/1.1" 304 0
[01/Jun/2020 06:47:25] "GET /static/images/bmr2.jpg HTTP/1.1" 304 0
Not Found: /
[01/Jun/2020 06:48:35] "GET / HTTP/1.1" 404 2433
[01/Jun/2020 11:37:04] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[01/Jun/2020 11:37:04] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /
[01/Jun/2020 11:38:38] "GET / HTTP/1.1" 404 2433
[01/Jun/2020 13:50:12] "GET /met/ HTTP/1.1" 200 1959
Not Found: /favicon.ico
[01/Jun/2020 13:50:12] "GET /favicon.ico HTTP/1.1" 404 2484
[01/Jun/2020 13:52:34] "GET /bmr/ HTTP/1.1" 200 1671
[01/Jun/2020 16:52:02] "GET /met/ HTTP/1.1" 200 1959
Not Found: /
[01/Jun/2020 17:48:53] "GET / HTTP/1.1" 404 2433
Not Found: /
[02/Jun/2020 04:08:34] "GET / HTTP/1.1" 404 2433
Invalid HTTP_HOST header: 'ip-172-31-24-200.us-west-1.compute.internal:5000'. You may need to add 'ip-172-31-24-200.us-west-1.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[02/Jun/2020 05:14:34] "GET / HTTP/1.0" 400 62238
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[02/Jun/2020 05:14:34] "GET / HTTP/1.0" 500 59
----------------------------------------
Exception happened during processing of request from ('209.17.97.50', 60865)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
Not Found: /
[02/Jun/2020 09:36:43] "GET / HTTP/1.1" 404 2433
Not Found: /
[02/Jun/2020 10:04:57] "GET /bmr/ HTTP/1.1" 200 1671
[02/Jun/2020 10:04:57] "GET / HTTP/1.1" 404 2433
[02/Jun/2020 10:04:57] "GET /met/ HTTP/1.1" 200 1959
Not Found: /favicon.ico
[02/Jun/2020 10:04:57] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[02/Jun/2020 10:04:57] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /
[02/Jun/2020 10:06:02] "GET / HTTP/1.1" 404 2433
[02/Jun/2020 10:37:42] "GET /bmr/ HTTP/1.1" 200 1671
[02/Jun/2020 10:37:42] "GET /met/ HTTP/1.1" 200 1959
Not Found: /favicon.ico
[02/Jun/2020 10:37:42] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[02/Jun/2020 10:37:42] "GET /favicon.ico HTTP/1.1" 404 2484
Invalid HTTP_HOST header: 'ip.ws.126.net:443'. You may need to add 'ip.ws.126.net' to ALLOWED_HOSTS.
Bad Request: /ip.ws.126.net:443
[02/Jun/2020 11:56:44] "CONNECT ip.ws.126.net:443 HTTP/1.1" 400 61861
[02/Jun/2020 12:05:58] "GET /met/ HTTP/1.1" 200 1959
[02/Jun/2020 12:05:58] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[02/Jun/2020 12:05:59] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[02/Jun/2020 12:05:59] "GET /favicon.ico HTTP/1.1" 404 2484
[02/Jun/2020 12:24:02] "GET /met/ HTTP/1.1" 200 1959
[02/Jun/2020 12:24:02] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[02/Jun/2020 12:24:02] "GET /favicon.ico HTTP/1.1" 404 2484
[02/Jun/2020 16:13:54] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[02/Jun/2020 16:13:54] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[02/Jun/2020 16:13:55] "GET /favicon.ico HTTP/1.1" 404 2484
[02/Jun/2020 16:19:36] "GET /met/ HTTP/1.1" 200 1959
[02/Jun/2020 16:29:08] "GET /bmr/ HTTP/1.1" 200 1671
[02/Jun/2020 17:43:42] "GET /met/ HTTP/1.1" 200 1959
Not Found: /
[02/Jun/2020 19:49:57] "GET / HTTP/1.1" 404 2433
Invalid HTTP_HOST header: 'ip-172-31-24-200.us-west-1.compute.internal:5000'. You may need to add 'ip-172-31-24-200.us-west-1.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[02/Jun/2020 20:55:32] "GET / HTTP/1.0" 400 62238
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[02/Jun/2020 20:55:32] "GET / HTTP/1.0" 500 59
----------------------------------------
Exception happened during processing of request from ('209.17.96.10', 50844)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
Not Found: /
[02/Jun/2020 23:35:49] "GET / HTTP/1.1" 404 2428
Not Found: /favicon.ico
[02/Jun/2020 23:35:50] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /
[02/Jun/2020 23:54:46] "GET / HTTP/1.1" 404 2433
Not Found: /
[03/Jun/2020 04:19:42] "GET / HTTP/1.1" 404 2433
[03/Jun/2020 07:50:00] "GET /met/ HTTP/1.1" 200 1959
[03/Jun/2020 07:50:00] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[03/Jun/2020 07:50:00] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[03/Jun/2020 07:50:00] "GET /favicon.ico HTTP/1.1" 404 2484
Invalid HTTP_HOST header: 'ip-172-31-24-200.us-west-1.compute.internal:5000'. You may need to add 'ip-172-31-24-200.us-west-1.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[03/Jun/2020 08:26:04] "GET / HTTP/1.0" 400 62282
[03/Jun/2020 08:39:35] "GET /met/ HTTP/1.1" 200 1959
[03/Jun/2020 08:39:35] "GET /static/css/style2.css HTTP/1.1" 200 596
[03/Jun/2020 08:39:37] "GET /static/images/met2.jpg HTTP/1.1" 200 157171
Not Found: /favicon.ico
[03/Jun/2020 08:39:38] "GET /favicon.ico HTTP/1.1" 404 2484
[03/Jun/2020 15:53:12] "GET /met/ HTTP/1.1" 200 1959
[03/Jun/2020 16:43:48] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[03/Jun/2020 16:43:48] "GET /favicon.ico HTTP/1.1" 404 2484
Not Found: /favicon.ico
[03/Jun/2020 16:43:48] "GET /favicon.ico HTTP/1.1" 404 2484
[03/Jun/2020 16:46:22] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /
[03/Jun/2020 16:46:26] "GET / HTTP/1.1" 404 2433
[03/Jun/2020 16:46:30] "GET /met/ HTTP/1.1" 200 1959
[03/Jun/2020 16:46:30] "GET /static/css/style2.css HTTP/1.1" 304 0
[03/Jun/2020 16:46:31] "GET /static/images/met2.jpg HTTP/1.1" 304 0
Not Found: /favicon.ico
[03/Jun/2020 16:48:52] "GET /favicon.ico HTTP/1.1" 404 2484
/home/ubuntu/work/MET-Calculator/met/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.
May 31, 2020 - 18:44:31
Django version 3.0.6, using settings 'met.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[04/Jun/2020 16:54:44] "GET /calculator/ HTTP/1.1" 200 3298
[04/Jun/2020 16:54:46] "GET /calculator/ HTTP/1.1" 200 3298
[04/Jun/2020 16:55:11] "POST /calculator/ HTTP/1.1" 200 2878
[04/Jun/2020 16:55:11] "GET /static/css/style2.css HTTP/1.1" 304 0
Watching for file changes with StatReloader
[04/Jun/2020 16:56:31] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 16:56:39] "POST /calculator/ HTTP/1.1" 200 2877
[04/Jun/2020 16:56:42] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 16:56:48] "POST /calculator/ HTTP/1.1" 200 2877
[04/Jun/2020 16:58:56] "GET /met/ HTTP/1.1" 200 2154
Internal Server Error: /met/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/work/MET-Calculator/simple/views.py", line 41, in MET
    mymet  = metvalue(float(act), int(level), int(hours), int(minutes))
ValueError: invalid literal for int() with base 10: '0.01'
[04/Jun/2020 16:59:11] "POST /met/ HTTP/1.1" 500 67674
[04/Jun/2020 16:59:37] "GET /bmr/ HTTP/1.1" 200 1671
[04/Jun/2020 16:59:38] "GET /static/css/style.css HTTP/1.1" 304 0
[04/Jun/2020 17:02:00] "GET /bmr/ HTTP/1.1" 200 1671
[04/Jun/2020 17:02:00] "GET /met/ HTTP/1.1" 200 2154
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[04/Jun/2020 17:06:06] "GET /bmr/ HTTP/1.1" 200 1671
Watching for file changes with StatReloader
[04/Jun/2020 17:14:57] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 17:15:15] "POST /calculator/ HTTP/1.1" 200 2879
[04/Jun/2020 17:15:20] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 17:21:29] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 17:22:27] "POST /calculator/ HTTP/1.1" 200 2878
[04/Jun/2020 17:22:55] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 17:22:57] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 17:22:59] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 17:35:02] "GET /met/ HTTP/1.1" 200 2154
[04/Jun/2020 17:35:02] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[04/Jun/2020 17:35:02] "GET /favicon.ico HTTP/1.1" 404 2614
Not Found: /favicon.ico
[04/Jun/2020 17:35:02] "GET /favicon.ico HTTP/1.1" 404 2614
[04/Jun/2020 17:38:35] "GET /met/ HTTP/1.1" 200 2154
Not Found: /favicon.ico
[04/Jun/2020 17:38:35] "GET /favicon.ico HTTP/1.1" 404 2614
[04/Jun/2020 18:10:33] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 18:10:33] "GET /static/css/style2.css HTTP/1.1" 200 1025
[04/Jun/2020 18:10:34] "GET /static/images/met2.jpg HTTP/1.1" 200 157171
[04/Jun/2020 18:11:28] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 18:11:29] "GET /static/css/style2.css HTTP/1.1" 200 1025
[04/Jun/2020 18:14:28] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 18:14:29] "GET /static/css/style2.css HTTP/1.1" 200 1025
[04/Jun/2020 18:14:30] "GET /static/images/met2.jpg HTTP/1.1" 200 157171
Not Found: /favicon.ico
[04/Jun/2020 18:14:31] "GET /favicon.ico HTTP/1.1" 404 2614
[04/Jun/2020 18:14:39] "GET /bmr/ HTTP/1.1" 200 1671
[04/Jun/2020 18:17:57] "POST /calculator/ HTTP/1.1" 200 2878
[04/Jun/2020 18:19:58] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 18:20:12] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 18:20:12] "POST /calculator/ HTTP/1.1" 200 2879
[04/Jun/2020 18:20:28] "GET /calculator/ HTTP/1.1" 200 3286
[04/Jun/2020 18:23:56] "POST /calculator/ HTTP/1.1" 200 2878
/home/ubuntu/work/MET-Calculator/simple/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.
June 04, 2020 - 17:14:49
Django version 3.0.6, using settings 'met.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.
7.5 0.01 2 3
45
45
6.0 0.03 3 4
72
117
7.5 0.01 5 6
225
342
7.5 0.01 3 4
90
90
7.5 0.01 2 3
45
45
7.5 0.01 2 3
45
45
7.5 0.02 3 4
90
135
3.0 0.02 1 30
90
90
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[04/Jun/2020 19:40:22] "GET /calculator/ HTTP/1.1" 200 3773
[04/Jun/2020 19:43:01] "GET /calculator/ HTTP/1.1" 200 3773
[04/Jun/2020 19:55:49] "GET /calculator/ HTTP/1.1" 200 3773
[04/Jun/2020 19:55:50] "GET /static/css/style2.css HTTP/1.1" 200 1025
[04/Jun/2020 19:55:51] "GET /static/images/met2.jpg HTTP/1.1" 200 157171
[04/Jun/2020 19:56:38] "POST /calculator/ HTTP/1.1" 200 2995
Invalid HTTP_HOST header: 'ip-172-31-24-200.us-west-1.compute.internal:5000'. You may need to add 'ip-172-31-24-200.us-west-1.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[05/Jun/2020 00:12:32] "GET / HTTP/1.0" 400 62243
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[05/Jun/2020 00:12:32] "GET / HTTP/1.0" 500 59
----------------------------------------
Exception happened during processing of request from ('209.17.96.42', 50291)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
Not Found: /
[05/Jun/2020 02:38:12] "GET / HTTP/1.1" 404 2563
Not Found: /favicon.ico
[05/Jun/2020 04:40:29] "GET /favicon.ico HTTP/1.1" 404 2614
[05/Jun/2020 04:40:30] "GET /bmr/ HTTP/1.1" 200 1671
Not Found: /favicon.ico
[05/Jun/2020 04:40:30] "GET /favicon.ico HTTP/1.1" 404 2614
Watching for file changes with StatReloader
[05/Jun/2020 08:25:32] "GET /calculator/ HTTP/1.1" 200 4053
[05/Jun/2020 08:37:33] "GET /calculator/ HTTP/1.1" 200 4053
[05/Jun/2020 08:37:33] "GET /static/css/style2.css HTTP/1.1" 304 0
[05/Jun/2020 08:37:34] "GET /static/images/met2.jpg HTTP/1.1" 304 0
[05/Jun/2020 08:38:15] "POST /calculator/ HTTP/1.1" 200 3961
[05/Jun/2020 08:50:54] "POST /calculator/ HTTP/1.1" 200 3962
[05/Jun/2020 08:54:15] "GET /calculator/ HTTP/1.1" 200 4053
/home/ubuntu/work/MET-Calculator/simple/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.
June 05, 2020 - 08:24:40
Django version 3.0.6, using settings 'met.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.
cycling|7.5 0.01 0 58
435
435
cycling|7.5 0.01 0 58
435
435
Watching for file changes with StatReloader
[05/Jun/2020 08:59:13] "GET /calculator/ HTTP/1.1" 200 4053
Internal Server Error: /calculator/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/work/MET-Calculator/simple/views.py", line 80, in calc
    weight_in_kgs = float(weight * 0.45359237)
TypeError: can't multiply sequence by non-int of type 'float'
[05/Jun/2020 09:00:27] "POST /calculator/ HTTP/1.1" 500 71197
/home/ubuntu/work/MET-Calculator/simple/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.
June 05, 2020 - 08:58:59
Django version 3.0.6, using settings 'met.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.
pilates|3 0.01 0 30
90
Watching for file changes with StatReloader
[05/Jun/2020 09:01:35] "GET /calculator/ HTTP/1.1" 200 4053
[05/Jun/2020 09:01:49] "POST /calculator/ HTTP/1.1" 200 3960
/home/ubuntu/work/MET-Calculator/simple/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 4 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.
June 05, 2020 - 09:01:31
Django version 3.0.6, using settings 'met.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.
pilates|3 0.01 0 30
90
90
